name: Regression suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

	  steps:
	   - name: checkout code
	     uses: actions/checkout@v2
	
	   - name: set up python
	     uses: actions/setup-python@v2
	     with:
	       python-versions: "3.13.1"
	
	   - name : Install dependencies
	     run: |
	       python -m pip install --upgrade pip
	       pip install -r requirements.txt
	
		 - name : Run Tests
			 run: |
					pytest -s --html=report.html -self-contained-html
	
	   - name: upload report
			 uses: actions/upload-artifact@v2
	     with:
					name: pytest-report
					path: report.html
				









